# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 631fc834ec8434026cdfd287c24ded747884f88e02b3e371edaa9ae656d9bfd4fb53cd3cb9c5d65084b51e7dab7ac9be7a071633815b0c4b49e8dbf90472c3e6

test:
  secret_key_base: 641d520ae041a26466f0da07202cb7505951b6c353ad77fdaa9c123b643c11fc2782d3a04e689b72938869e07a7f193d2891a8f355036e57f3ac4244d7691738

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
